export const ZONES = [
  {id:"vendors",name:"Vendors & bookings",em:"\ud83e\uddfe"},
  {id:"venue",name:"Venue & church",em:"\u26ea"},
  {id:"guests",name:"Guest management",em:"\ud83d\udc8c"},
  {id:"design",name:"Design & styling",em:"\ud83c\udf38"},
  {id:"personal",name:"Bridal party & personal",em:"\ud83d\udc8d"},
  {id:"food",name:"Food & drink",em:"\ud83c\udf70"},
  {id:"legal",name:"Legal & admin",em:"\ud83d\udcdd"},
  {id:"finalweek",name:"Final week",em:"\ud83d\udcc5"},
  {id:"morning",name:"Morning of",em:"\u2600\ufe0f"},
  {id:"ceremony",name:"Ceremony",em:"\ud83d\udc92"},
  {id:"gap",name:"The gap",em:"\ud83d\udcf7"},
  {id:"reception",name:"Reception",em:"\ud83c\udf89"},
  {id:"endofnight",name:"End of night",em:"\ud83c\udf19"},
  {id:"postwedding",name:"Post-wedding",em:"\u2764\ufe0f"},
]

export const STATUSES: Record<string, {bg:string,tx:string,lb:string}> = {
  "not-started":{bg:"#f0eeea",tx:"#8a8883",lb:"Not started"},
  "in-progress":{bg:"#e8f0f8",tx:"#4a7a9e",lb:"In progress"},
  "waiting":{bg:"#fef5e7",tx:"#9a7a3a",lb:"Waiting on someone"},
  "needs-discussion":{bg:"#f0ecf8",tx:"#6a5a8f",lb:"Needs discussion"},
  "done":{bg:"#e8f5ee",tx:"#3a7a5a",lb:"Done"},
}

export const BUDGET_STATES: Record<string, {bg:string,tx:string,lb:string}> = {
  quoted:{bg:"#f0ecf8",tx:"#6a5a8f",lb:"Quoted"},
  deposited:{bg:"#fef5e7",tx:"#9a7a3a",lb:"Deposited"},
  paid:{bg:"#e8f5ee",tx:"#3a7a5a",lb:"Paid in full"},
}

export const PHASES = [
  {id:"mar",name:"March 2026",color:"#c97a6a"},
  {id:"apr",name:"April",color:"#b98a6a"},
  {id:"may",name:"May",color:"#a99a6a"},
  {id:"jun",name:"June",color:"#8aaa6a"},
  {id:"jul",name:"July \u2013 August",color:"#6a9a8a"},
  {id:"sep",name:"September \u2013 October",color:"#6a8aaa"},
  {id:"nov",name:"November (final weeks)",color:"#8a6aaa"},
  {id:"week",name:"Final week",color:"#c97a8a"},
  {id:"after",name:"After the wedding",color:"#9a8a7a"},
]

export const BUDGET_CATS = [
  {id:"venue",name:"Venue & logistics",em:"\u26ea"},
  {id:"food",name:"Food & drink",em:"\ud83c\udf70"},
  {id:"bridal",name:"Bridal prep",em:"\ud83d\udc8d"},
  {id:"decor",name:"Styling & decor",em:"\ud83c\udf38"},
  {id:"entertainment",name:"Entertainment",em:"\ud83c\udfb5"},
  {id:"other",name:"Other",em:"\ud83d\udccc"},
]

export type Task = {
  id: string; zone: string; task: string; status: string;
  owner: string; dep: string; notes: string; phase: string; ord: number;
}

export type BudgetItem = {
  id: string; cat: string; amt: number; st: string; n: string; g: string;
}

export type TimelineEvent = {
  id: string; t: string; e: string; w: string; big?: boolean;
}

export const INITIAL_TASKS: Task[] = [
  {id:"t1",zone:"legal",task:"Lodge NOIM with priest",status:"not-started",owner:"",dep:"",notes:"Must be 1+ month before. Need original birth certs/passports.",phase:"mar",ord:0},
  {id:"t2",zone:"legal",task:"Gather original birth certs / passports",status:"not-started",owner:"",dep:"",notes:"Needed for NOIM.",phase:"mar",ord:1},
  {id:"t3",zone:"venue",task:"Check church wheelchair access for mum",status:"not-started",owner:"",dep:"",notes:"Mum is in wheelchair.",phase:"mar",ord:2},
  {id:"t4",zone:"ceremony",task:"One more meeting with priest",status:"not-started",owner:"Both",dep:"",notes:"NOIM, readings, music rules, accessibility, rehearsal.",phase:"mar",ord:3},
  {id:"t5",zone:"guests",task:"Chase ~50 non-RSVP guests",status:"not-started",owner:"Both",dep:"",notes:"Deadline passed Feb. ~50% haven't responded.",phase:"mar",ord:4},
  {id:"t6",zone:"vendors",task:"Formally ask Dom to MC",status:"not-started",owner:"",dep:"",notes:"He hasn't been asked yet!",phase:"mar",ord:5},
  {id:"t7",zone:"vendors",task:"Confirm speakers for DJ friend",status:"not-started",owner:"",dep:"",notes:"Family member might have them. Ask + test.",phase:"mar",ord:6},
  {id:"t8",zone:"venue",task:"Venue manager meeting",status:"not-started",owner:"Both",dep:"",notes:"Extra hour cost, setup, bar tab, draping, AV, pack-down.",phase:"mar",ord:7},
  {id:"t9",zone:"venue",task:"Check noise curfew",status:"not-started",owner:"",dep:"",notes:"Kingston Council. Mentone residential area.",phase:"mar",ord:8},
  {id:"t10",zone:"morning",task:"Figure out florist delivery logistics",status:"not-started",owner:"",dep:"",notes:"Bouquets to bride, buttonholes to groom (45 min away!), centrepieces to venue. Pickup day before?",phase:"mar",ord:9},
  {id:"t11",zone:"vendors",task:"Finalise menu with caterer",status:"in-progress",owner:"",dep:"",notes:"$75/head, flexible. Second meeting needed.",phase:"apr",ord:0},
  {id:"t12",zone:"vendors",task:"Decide choir vs cheaper alternative",status:"needs-discussion",owner:"Both",dep:"",notes:"$1,600 quote. Find cheaper or friend?",phase:"apr",ord:1},
  {id:"t13",zone:"personal",task:"Buy groom suit + bow tie",status:"not-started",owner:"",dep:"",notes:"Clean black, bow tie.",phase:"apr",ord:2},
  {id:"t14",zone:"personal",task:"Buy wedding rings",status:"in-progress",owner:"Both",dep:"",notes:"Currently looking. 4-6 weeks.",phase:"apr",ord:3},
  {id:"t15",zone:"food",task:"Source affordable cake for 100",status:"not-started",owner:"Both",dep:"",notes:"Small cutting cake + sheet cakes.",phase:"apr",ord:4},
  {id:"t16",zone:"morning",task:"Decide bride getting-ready location",status:"needs-discussion",owner:"Both",dep:"",notes:"Home vs grandparents. Photo space.",phase:"apr",ord:5},
  {id:"t17",zone:"venue",task:"Decide 9pm vs 10pm",status:"needs-discussion",owner:"Both",dep:"t8",notes:"Leaning 10pm. Need cost. 9pm = ~55 min dancing.",phase:"apr",ord:6},
  {id:"t18",zone:"food",task:"Decide bar tab amount",status:"needs-discussion",owner:"Both",dep:"t8",notes:"$2-3k typical.",phase:"apr",ord:7},
  {id:"t19",zone:"venue",task:"Confirm draping situation",status:"not-started",owner:"",dep:"t8",notes:"Meeting venue manager.",phase:"apr",ord:8},
  {id:"t20",zone:"venue",task:"Check church petal policy",status:"not-started",owner:"",dep:"",notes:"For flower girl.",phase:"apr",ord:9},
  {id:"t21",zone:"personal",task:"Finalise bridesmaids dresses",status:"in-progress",owner:"",dep:"",notes:"Almost sorted.",phase:"apr",ord:10},
  {id:"t22",zone:"personal",task:"Ask ring bearer cousins + parents",status:"not-started",owner:"Both",dep:"",notes:"3 kid cousins.",phase:"apr",ord:11},
  {id:"t23",zone:"personal",task:"Ask flower girl cousin + parents",status:"not-started",owner:"Both",dep:"t20",notes:"Check petal policy first.",phase:"apr",ord:12},
  {id:"t24",zone:"design",task:"Finalise centrepiece design",status:"in-progress",owner:"Both",dep:"",notes:"Half designed.",phase:"apr",ord:13},
  {id:"t25",zone:"food",task:"Confirm canapes for cocktail hour",status:"not-started",owner:"",dep:"t11",notes:"Included or extra?",phase:"may",ord:0},
  {id:"t26",zone:"vendors",task:"Confirm caterer + venue staff",status:"not-started",owner:"",dep:"t8",notes:"Ask at venue meeting.",phase:"may",ord:1},
  {id:"t27",zone:"legal",task:"Confirm 2 witnesses",status:"not-started",owner:"",dep:"",notes:"Must be 18+.",phase:"may",ord:2},
  {id:"t28",zone:"legal",task:"Research wedding insurance",status:"not-started",owner:"",dep:"",notes:"~$200-500.",phase:"may",ord:3},
  {id:"t29",zone:"ceremony",task:"Choose readings",status:"not-started",owner:"Both",dep:"t4",notes:"2 readings + psalm + gospel.",phase:"may",ord:4},
  {id:"t30",zone:"ceremony",task:"Assign readers",status:"not-started",owner:"Both",dep:"t29",notes:"After readings picked.",phase:"jun",ord:0},
  {id:"t31",zone:"personal",task:"Coordinate groomsmen suit colour",status:"not-started",owner:"",dep:"t13",notes:"Send reference to all 4.",phase:"jun",ord:1},
  {id:"t32",zone:"ceremony",task:"Lock processional order + music",status:"not-started",owner:"Both",dep:"",notes:"Groom at front, bridesmaids, bride with grandfather.",phase:"jun",ord:2},
  {id:"t33",zone:"reception",task:"Create family photo shot list",status:"not-started",owner:"Both",dep:"",notes:"Must-have groupings.",phase:"jun",ord:3},
  {id:"t34",zone:"gap",task:"Create setup crew game plan",status:"not-started",owner:"",dep:"t8",notes:"2-3 friends at 2pm.",phase:"jun",ord:4},
  {id:"t35",zone:"gap",task:"Figure out how DIY stuff gets to venue",status:"not-started",owner:"",dep:"",notes:"Car transport by 2pm.",phase:"jun",ord:5},
  {id:"t36",zone:"gap",task:"Assign guest greeter for 4pm",status:"not-started",owner:"",dep:"",notes:"You arrive at 5pm.",phase:"jun",ord:6},
  {id:"t37",zone:"design",task:"Source battery candles",status:"not-started",owner:"",dep:"",notes:"No real candles.",phase:"jun",ord:7},
  {id:"t38",zone:"vendors",task:"Source camcorders + film cameras",status:"not-started",owner:"",dep:"",notes:"DIY video plan.",phase:"jul",ord:0},
  {id:"t39",zone:"vendors",task:"Build DJ playlist",status:"not-started",owner:"Both",dep:"",notes:"Must-plays + do-not-plays.",phase:"jul",ord:1},
  {id:"t40",zone:"ceremony",task:"Book church rehearsal",status:"not-started",owner:"",dep:"",notes:"Usually night before.",phase:"jul",ord:2},
  {id:"t41",zone:"guests",task:"Compile dietary requirements",status:"not-started",owner:"",dep:"t5",notes:"Export from WithJoy.",phase:"sep",ord:0},
  {id:"t42",zone:"guests",task:"Build seating plan",status:"not-started",owner:"Both",dep:"t5",notes:"After RSVPs finalised.",phase:"sep",ord:1},
  {id:"t43",zone:"design",task:"Design + print nameplates",status:"not-started",owner:"",dep:"t42",notes:"Need final names.",phase:"sep",ord:2},
  {id:"t44",zone:"design",task:"Design + print shared menus",status:"not-started",owner:"",dep:"t11",notes:"Need finalised menu.",phase:"sep",ord:3},
  {id:"t45",zone:"design",task:"Welcome sign",status:"not-started",owner:"",dep:"",notes:"DIY or order?",phase:"sep",ord:4},
  {id:"t46",zone:"design",task:"Plan bridal table styling",status:"not-started",owner:"Both",dep:"",notes:"Elevated vs others.",phase:"sep",ord:5},
  {id:"t47",zone:"reception",task:"Build day-of run sheet",status:"not-started",owner:"Both",dep:"t17",notes:"Dom + caterer + DJ need copies.",phase:"sep",ord:6},
  {id:"t48",zone:"reception",task:"Brief speakers on length + tone",status:"not-started",owner:"",dep:"",notes:"25 min total max.",phase:"sep",ord:7},
  {id:"t49",zone:"reception",task:"Plan grand entrance",status:"not-started",owner:"Both",dep:"",notes:"Music? Dom announces?",phase:"sep",ord:8},
  {id:"t50",zone:"reception",task:"Assign family wrangler",status:"not-started",owner:"",dep:"",notes:"For group photos.",phase:"sep",ord:9},
  {id:"t51",zone:"morning",task:"Map bride morning timeline",status:"not-started",owner:"",dep:"t16",notes:"Backwards from 10:45.",phase:"sep",ord:10},
  {id:"t52",zone:"morning",task:"Create bridesmaid morning plan",status:"not-started",owner:"",dep:"t51",notes:"Arrival time, dress.",phase:"sep",ord:11},
  {id:"t53",zone:"morning",task:"Map groom morning timeline",status:"not-started",owner:"",dep:"",notes:"Leave by 10:30.",phase:"sep",ord:12},
  {id:"t54",zone:"endofnight",task:"Assign card box security",status:"not-started",owner:"Both",dep:"",notes:"Sober person. Cash inside.",phase:"sep",ord:13},
  {id:"t55",zone:"endofnight",task:"Assign pack-down crew",status:"not-started",owner:"",dep:"",notes:"Everything collected.",phase:"sep",ord:14},
  {id:"t56",zone:"endofnight",task:"Plan send-off / exit",status:"not-started",owner:"Both",dep:"t8",notes:"Sparklers? Venue rules.",phase:"sep",ord:15},
  {id:"t57",zone:"gap",task:"Assign hotel check-in person",status:"not-started",owner:"",dep:"",notes:"Richmond hotel.",phase:"sep",ord:16},
  {id:"t58",zone:"endofnight",task:"Arrange transport to hotel",status:"not-started",owner:"",dep:"",notes:"Uber or pre-book.",phase:"sep",ord:17},
  {id:"t59",zone:"finalweek",task:"Reconfirm ALL vendors",status:"not-started",owner:"",dep:"",notes:"Date, time, contact.",phase:"week",ord:0},
  {id:"t60",zone:"finalweek",task:"Send final headcount to caterer",status:"not-started",owner:"",dep:"t5",notes:"Dietary, vendor meals.",phase:"week",ord:1},
  {id:"t61",zone:"finalweek",task:"Distribute run sheet",status:"not-started",owner:"",dep:"t47",notes:"Dom, caterer, DJ, bridal party.",phase:"week",ord:2},
  {id:"t62",zone:"finalweek",task:"Send photographer shot list",status:"not-started",owner:"",dep:"t33",notes:"Family groupings.",phase:"week",ord:3},
  {id:"t63",zone:"finalweek",task:"Pack ceremony + reception supplies",status:"not-started",owner:"",dep:"",notes:"Everything for church + venue.",phase:"week",ord:4},
  {id:"t64",zone:"finalweek",task:"Charge ALL camcorders",status:"not-started",owner:"",dep:"",notes:"Night before.",phase:"week",ord:5},
  {id:"t65",zone:"finalweek",task:"Prepare tip envelopes",status:"not-started",owner:"",dep:"",notes:"Cash, labelled.",phase:"week",ord:6},
  {id:"t66",zone:"finalweek",task:"Break in wedding shoes",status:"not-started",owner:"Both",dep:"",notes:"Few evenings.",phase:"week",ord:7},
  {id:"t67",zone:"finalweek",task:"Final grooming",status:"not-started",owner:"Both",dep:"",notes:"3-5 days before.",phase:"week",ord:8},
  {id:"t68",zone:"postwedding",task:"Lodge marriage cert with BDM",status:"not-started",owner:"",dep:"",notes:"First week.",phase:"after",ord:0},
  {id:"t69",zone:"postwedding",task:"Send thank you cards",status:"not-started",owner:"Both",dep:"",notes:"2-3 weeks.",phase:"after",ord:1},
  {id:"t70",zone:"postwedding",task:"Collect all video footage",status:"not-started",owner:"",dep:"",notes:"Camcorders, phones.",phase:"after",ord:2},
]

export const INITIAL_BUDGET: BudgetItem[] = [
  {id:"b1",cat:"Venue",amt:0,st:"deposited",n:"Deposit paid. Confirm total",g:"venue"},
  {id:"b2",cat:"Church",amt:0,st:"deposited",n:"Confirm total",g:"venue"},
  {id:"b3",cat:"Catering (~100)",amt:7500,st:"quoted",n:"~$75/head",g:"food"},
  {id:"b4",cat:"Florist",amt:1200,st:"deposited",n:"$500 of $1,200",g:"decor"},
  {id:"b5",cat:"Photographer",amt:0,st:"deposited",n:"Fill in total",g:"other"},
  {id:"b6",cat:"Makeup",amt:200,st:"deposited",n:"Trial upcoming",g:"bridal"},
  {id:"b7",cat:"Hair (friend)",amt:0,st:"quoted",n:"Confirm cost",g:"bridal"},
  {id:"b8",cat:"DJ (friend)",amt:0,st:"quoted",n:"$50/hr",g:"entertainment"},
  {id:"b9",cat:"Sprinter",amt:800,st:"deposited",n:"5hrs",g:"venue"},
  {id:"b10",cat:"Car hire",amt:330,st:"quoted",n:"3hrs",g:"venue"},
  {id:"b11",cat:"Wedding dress",amt:0,st:"paid",n:"Track cost",g:"bridal"},
  {id:"b12",cat:"Groom suit",amt:0,st:"quoted",n:"Black + bow tie",g:"bridal"},
  {id:"b13",cat:"Rings",amt:0,st:"quoted",n:"Looking",g:"bridal"},
  {id:"b14",cat:"Cake",amt:0,st:"quoted",n:"Not sourced",g:"food"},
  {id:"b15",cat:"Choir / music",amt:1600,st:"quoted",n:"Or cheaper",g:"entertainment"},
  {id:"b16",cat:"Bar tab",amt:0,st:"quoted",n:"Decide amount",g:"food"},
  {id:"b17",cat:"Extra hour",amt:0,st:"quoted",n:"Need cost",g:"venue"},
  {id:"b18",cat:"Draping",amt:0,st:"quoted",n:"TBD",g:"decor"},
  {id:"b19",cat:"Invitations",amt:0,st:"paid",n:"Sent",g:"decor"},
  {id:"b20",cat:"Stationery",amt:0,st:"quoted",n:"Nameplates, menus",g:"decor"},
  {id:"b21",cat:"Hotel night",amt:0,st:"deposited",n:"Richmond",g:"venue"},
  {id:"b22",cat:"Insurance",amt:0,st:"quoted",n:"Research",g:"venue"},
  {id:"b23",cat:"Misc",amt:0,st:"quoted",n:"Tips, emergency",g:"other"},
]

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {id:"tl1",t:"7:30am",e:"Hair friend arrives",w:"Hair friend"},
  {id:"tl2",t:"~9:00am",e:"Makeup artist arrives",w:"MUA"},
  {id:"tl3",t:"~9:30am",e:"Bridesmaids arrive",w:"4 bridesmaids"},
  {id:"tl4",t:"~10:15am",e:"Morning photos",w:"Family cameras"},
  {id:"tl5",t:"10:30am",e:"Groom + groomsmen leave",w:"45 min drive"},
  {id:"tl6",t:"10:45am",e:"Sprinter picks up bride",w:"Sprinter"},
  {id:"tl7",t:"11:15am",e:"Arrive at church",w:"Everyone"},
  {id:"tl8",t:"11:30am",e:"Guests arrive + seated",w:"100 guests"},
  {id:"tl9",t:"12:00pm",e:"Ceremony",w:"Catholic mass",big:true},
  {id:"tl10",t:"~1:00pm",e:"Family photos outside church",w:"Photographer"},
  {id:"tl11",t:"~1:15pm",e:"Bride + groom depart",w:"$330 car"},
  {id:"tl12",t:"~1:30pm",e:"Photos at Ripponlea",w:"~1 hour"},
  {id:"tl13",t:"2:00pm",e:"Setup crew at venue",w:"Friends"},
  {id:"tl14",t:"~2:30pm",e:"Photos done",w:"Chill time"},
  {id:"tl15",t:"4:00pm",e:"Venue opens \u2014 cocktails",w:"Guests arrive",big:true},
  {id:"tl16",t:"5:00pm",e:"Grand entrance",w:"Dom announces",big:true},
  {id:"tl17",t:"5:30pm",e:"MC welcome",w:"Dom"},
  {id:"tl18",t:"6:00pm",e:"Dinner",w:"Sit-down",big:true},
  {id:"tl19",t:"~7:15pm",e:"Speeches",w:"~25 min",big:true},
  {id:"tl20",t:"~7:40pm",e:"First dance",w:"Custom song",big:true},
  {id:"tl21",t:"~7:50pm",e:"Dance floor opens!",w:"DJ friend",big:true},
  {id:"tl22",t:"~9:45pm",e:"Last song + send-off",w:""},
  {id:"tl23",t:"10:00pm",e:"Venue closes",w:"",big:true},
  {id:"tl24",t:"10:00pm",e:"Pack-down",w:"Crew TBD"},
  {id:"tl25",t:"~10:15pm",e:"Uber to hotel",w:"Richmond"},
]
